name: CreatRecipeUI
version: '1.0-SNAPSHOT'
main: com.github.wcy6457.creatRecipeUI.CreatRecipeUI
api-version: '1.21'

commands:
  cru:
    description: Main command entry point
    usage: /cru
    permission: cru.use
    permission-message: "§cAccess denied: insufficient permissions."